
WEATHER_ICONS = {
    '01n': "fa-moon",
    '01d': "fa-sun",
    '02n': "fa-cloud-moon",
    '02d': "fa-cloud-sun",
    '03n': "fa-cloud-moon",
    '03d': "fa-cloud-sun",
    '04n': "fa-cloud-moon",
    '04d': "fa-cloud-sun",
    '09n': "fa-cloud",
    '09d': "fa-cloud",
    '10n': "fa-cloud-rain",
    '10d': "fa-cloud-rain",
    '11n': "fa-bolt",
    '11d': "fa-bolt",
    '13n': "fa-snowflake",
    '13d': "fa-snowflake",
    '50n': "fa-smog",
    '50d': "fa-smog",
}